import express from 'express';
import axios from 'axios';
const router=express.Router();
const baseUrl=()=>process.env.MPESA_ENV==='production'?'https://api.safaricom.co.ke':'https://sandbox.safaricom.co.ke';
async function getAccessToken(){ const auth=Buffer.from(`${process.env.MPESA_CONSUMER_KEY}:${process.env.MPESA_CONSUMER_SECRET}`).toString('base64'); const response=await axios.get(`${baseUrl()}/oauth/v1/generate?grant_type=client_credentials`,{headers:{Authorization:`Basic ${auth}`}}); return response.data.access_token; }
function timestamp(){ const now=new Date(); const pad=n=>String(n).padStart(2,'0'); return `${now.getFullYear()}${pad(now.getMonth()+1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`; }
const password=(ts)=>Buffer.from(`${process.env.MPESA_SHORTCODE}${process.env.MPESA_PASSKEY}${ts}`).toString('base64');
router.post('/pay', async (req,res)=>{ try{ const { phone, amount, accountReference, transactionDesc }=req.body; if(!phone||!amount) return res.status(400).json({error:'phone and amount are required'}); const token=await getAccessToken(); const ts=timestamp(); const normalized=String(phone).replace(/^0/,'254'); const payload={ BusinessShortCode:process.env.MPESA_SHORTCODE, Password:password(ts), Timestamp:ts, TransactionType:process.env.MPESA_TRANSACTION_TYPE||'CustomerPayBillOnline', Amount:Math.round(Number(amount)), PartyA:normalized, PartyB:process.env.MPESA_PARTYB||process.env.MPESA_SHORTCODE, PhoneNumber:normalized, CallBackURL:process.env.MPESA_CALLBACK_URL, AccountReference:accountReference||'HOUSE-OF-BRENE', TransactionDesc:transactionDesc||'House of Brene order' }; const response=await axios.post(`${baseUrl()}/mpesa/stkpush/v1/processrequest`,payload,{headers:{Authorization:`Bearer ${token}`}}); res.json({ok:true,checkoutRequestId:response.data.CheckoutRequestID,merchantRequestId:response.data.MerchantRequestID,customerMessage:response.data.CustomerMessage||'STK push sent successfully'});} catch(error){res.status(500).json({error:error.response?.data?.errorMessage||error.response?.data?.error||error.message});}});
router.post('/callback',(req,res)=>{ console.log('M-Pesa callback:', JSON.stringify(req.body,null,2)); res.json({ResultCode:0,ResultDesc:'Accepted'}); });
export default router;
